// GENERATED by scripts/generate-court-bitmaps.mjs - do not edit by hand.
import type { ImageSourcePropType } from 'react-native'

import type { Suit } from '../../types'
import type { CourtRank } from '../court'

/** A pre-rasterized bitmap for one (suit, rank) court figure - see the script's own header comment
 * for why these exist alongside the live DecoratedCourtFigure.tsx vector art. Each is a real RN
 * image asset reference (a Metro/webpack-resolved id on native, a URL on web via react-native-web's
 * asset loader) - render with a plain <Image>, e.g. DecoratedCourtFigureBitmap. */
export const courtBitmaps: Record<Suit, Record<CourtRank, ImageSourcePropType>> = {
  clubs: {
    jack: require('./clubs-jack.png') as ImageSourcePropType,
    queen: require('./clubs-queen.png') as ImageSourcePropType,
    king: require('./clubs-king.png') as ImageSourcePropType
  },
  diamonds: {
    jack: require('./diamonds-jack.png') as ImageSourcePropType,
    queen: require('./diamonds-queen.png') as ImageSourcePropType,
    king: require('./diamonds-king.png') as ImageSourcePropType
  },
  hearts: {
    jack: require('./hearts-jack.png') as ImageSourcePropType,
    queen: require('./hearts-queen.png') as ImageSourcePropType,
    king: require('./hearts-king.png') as ImageSourcePropType
  },
  spades: {
    jack: require('./spades-jack.png') as ImageSourcePropType,
    queen: require('./spades-queen.png') as ImageSourcePropType,
    king: require('./spades-king.png') as ImageSourcePropType
  }
}

/** The aspect (width / height) every bitmap above was rasterized at - see the script's WIDTH/HEIGHT
 * derivation from CardFace's real content-area shape. Consumers sizing the bitmap to a different box
 * should letterbox/stretch consistently with this, not assume a square or a card's full aspect. */
export const COURT_BITMAP_ASPECT = 0.941176
