// AUTO-GENERATED by scripts/generate-card-artwork.mjs - see NOTICE.md and LICENSE.
// Do not hand-edit; regenerate with: node scripts/generate-card-artwork.mjs <svg-cards.svg>

import type { DecoratedArt } from '../types';
import type { Rank, Suit } from '../../types';
import { spades } from './spades';
import { hearts } from './hearts';
import { diamonds } from './diamonds';
import { clubs } from './clubs';

export const decoratedDeck: Record<Suit, Record<Rank, DecoratedArt>> = {
  spades,
  hearts,
  diamonds,
  clubs,
};
